version: '3'
services:
  portainer:
    image: portainer/portainer:1.25.0
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
      - ./public:/public
    ports:
      - ${PANEL_APP_PORT_HTTP}:9000
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true