# https://taskfile.dev
version: '3'

vars:
  BUILD_VERSION:
    sh: git describe --tags --abbrev=0

env:
  BUILD_PATH: build
  WEB_PATH: frontend
  SERVER_PATH: backend
  MAIN: "cmd/server/main.go"
  APP_NAME: 1panel

tasks:
  build-web-tpl:
    label: "build-web-tpl -> {{.TASK}}"
    dir: "{{.WEB_PATH}}"
    cmds: 
        - npm install
        - npm run build:{{.WEB_MODE}}

  build-web-dev:
    cmds:
      - task: build-web-tpl
        vars: {
          TASK: "{{.TASK}}",
          WEB_MODE: dev
        }

  build-web-pro:
    cmds:
      - task: build-web-tpl
        vars: {
          TASK: "{{.TASK}}",
          WEB_MODE: pro
        }  

  copy-resource:
    cmds:
      - cp -rf deploy/* {{.BUILD_PATH}}/{{.APP_NAME}}-{{.BUILD_VERSION}}-{{.TASK}}

  build-bin-tpl:
    label: "build-bin-tpl -> {{.TASK}}"
    dir: "{{.SERVER_PATH}}"
    cmds:
      - |
        CGO_ENABLED=1 GOOS={{.GOOS}} GOARCH={{.GOARCH}} GOARM={{.GOARM}} GOMIPS={{.GOMIPS}} GOAMD64={{.GOAMD64}} go build -trimpath -ldflags '-s -w --extldflags "-static -fpic"' -tags 'osusergo,netgo' -o ../{{.BUILD_PATH}}/{{.APP_NAME}}-{{.BUILD_VERSION}}-{{.TASK}}/{{.APP_NAME}} ../{{.MAIN}}
      - task: copy-resource
        vars: {
          TASK: "{{.TASK}}",
          GOOS: "{{.GOOS}}",
          GOARCH: "{{.GOARCH}}"
        }       

  linux-amd64:
    dir: "{{.SERVER_PATH}}"
    cmds:
      - task: build-bin-tpl
        vars: {
          TASK: "{{.TASK}}",
          GOOS: linux,
          GOARCH: amd64
        }
  linux-amd64-v2:
    dir: "{{.SERVER_PATH}}"
    cmds:
      - task: build-bin-tpl
        vars: {
          TASK: "{{.TASK}}",
          GOOS: linux,
          GOARCH: amd64,
          GOAMD64: v2
        }
  linux-amd64-v3:
    dir: "{{.SERVER_PATH}}"
    cmds:
      - task: build-bin-tpl
        vars: {
          TASK: "{{.TASK}}",
          GOOS: linux,
          GOARCH: amd64,
          GOAMD64: v3
        }
  linux-amd64-v4:
    dir: "{{.SERVER_PATH}}"
    cmds:
      - task: build-bin-tpl
        vars: {
          TASK: "{{.TASK}}",
          GOOS: linux,
          GOARCH: amd64,
          GOAMD64: v4
        }

  default:
    cmds:
      - task: build-web-dev
      - task: linux-amd64
      - task: linux-amd64-v2
      - task: linux-amd64-v3
      - task: linux-amd64-v4
