version: '3'
services:
  aria-ng:
    # 镜像名称
    image: aria-ng:1.3.3
    # 容器名称
    container_name: ${CONTAINER_NAME}     
    # 自启动
    restart: unless-stopped
    # 设定上下文根目录，然后以该目录为准指定 Dockerfile，赋值Dockerfile 中的 ARG 指令
    build: 
      context: .
      dockerfile: Dockerfile
    command: --port ${PANEL_APP_PORT_HTTP} --ipv6
    # 加入指定网络
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:6801
    volumes:
      - ./html:/var/www/html

networks:
  1panel-network:
    external: true