system:
  db_file: 1Panel.db
  base_dir: /opt
  mode: dev
  repo_url: https://resource.fit2cloud.com/1panel/package
  # repo_url: http://res.vcanbb.com/1panel/package
  # repo_url: https://raw.githubusercontent.com/adams549659584/1Panel/my-dev/package  
  is_demo: false
  port: 9999

log:
  # panic fatal error warn info debug trace
  level: info
  time_zone: Asia/Shanghai
  log_name: 1Panel
  log_suffix: .log
  max_backup: 10
