version: '3'
services:
  xui:
    # 镜像名称
    image: adams549659584/x-ui:0.3.2
    # 容器名称
    container_name: ${CONTAINER_NAME}
    # 自启动
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./db:/etc/x-ui
    environment:
      XUI_WEB_PORT: ${PANEL_APP_PORT_HTTP}
    labels:  
      createdBy: "Apps"        